routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', "DomaineController@accueil")->name('accueil');
Route::resource('domaine', 'DomaineController');
Route::resource('contact', 'ContactController');
Route::resource('image', 'ImageController');
Route::get('/voir', 'EmailController@voir')->name('voir');
Route::post('/send', 'EmailController@send')->name('send');

app/Contact.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    //
}

app/Domaine.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Image;

class Domaine extends Model
{
    public function images()
    {
      return $this->hasMany('App\Image');
    }
}

app/Image.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Domaine;

class Image extends Model
{
    public function domaine()
    {
        return $this->hasOne('App\Domaine');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use App\UserType;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function user_type()
    {
      return $this->hasOne('App\UserType');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DomaineController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Domaine;
use App\Image;

class DomaineController extends Controller
{

    public function accueil()
    {
        $domaines = Domaine::all();
        return view('accueil')->with('domaines', $domaines);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return redirect()->route('accueil');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('domaine.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //new Domaine = $request->input('libelle');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        
        $domaine = Domaine::find($id);
        return view('domaine.show')->with('domaine', $domaine);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/EmailController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Mail\ContactMail;
use Illuminate\Support\Facades\Mail;
use App\Contact;

class EmailController extends Controller
{
  public function send(Request $request){
    request()->validate ([
    'nom' => 'sometimes|required|between:3,50',
    'email' => 'sometimes|required|email',
    'sujet' => 'sometimes|required|max:255',
    'message' => 'sometimes|required|max:2000',
      ]);

    $contact = new Contact;
    $contact->nom = $request->input('nom');
    $contact->email = $request->input('email');
    $contact->sujet = $request->input('sujet');
    $contact->message = $request->input('message');
    $contact->save();

    $to_email = "rfejoz@gmail.com";

    Mail::to($to_email)->send(new ContactMail($request));

    return view('accueil')->with('status', "Bien envoyé");


  }
  public function voir(){
    return view('email.send');
  }
}

app/Http/Controllers/ImageControlleur.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ImageControlleur extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $images = Image::all();
        return view('image.index')->with('images', $images);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $images = Image::all()->where("domaine_id", "=", $id);
        //return view('image.show')->with('images', $images);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/accueil.blade.php
@extends('template')

@section('title')
Accueil
@endsection
@section('content')
<h1>Didier Marechal</h1>

<p>Ipsam vero urbem Byzantiorum fuisse refertissimam atque ornatissimam signis quis ignorat? Quae illi, exhausti sumptibus bellisque maximis, cum omnis Mithridaticos impetus totumque Pontum armatum affervescentem in Asiam atque erumpentem, ore repulsum et cervicibus interclusum suis sustinerent, tum, inquam, Byzantii et postea signa illa et reliqua urbis ornanemta sanctissime custodita tenuerunt.</p>

<div class="card-deck">
  @foreach($domaines as $domaine)
  <div class="card">
    <img class="card-img-top img-fluid" src="{{$domaine->url}}" alt="Card image cap" >
    <div class="card-body">
      <h5 class="card-title">{{$domaine->libelle}}</h5>
      <p class="card-text">Images prises au cours d'interventions.</p>
      <a type="button" href="{{route('domaine.show', ['domaine' => $domaine->id])}}" class="btn btn-primary">Voir</a>
    </div>
  </div>
    @endforeach
</div>
@stop

resources/views/contact/create.blade.php
@extends('template')

@section('title')
Contact
@stop
@section('content')

<section class="mb-4">

    <h2 class="h1-responsive font-weight-bold text-center my-4">Contactez moi</h2>

    <p class="text-center w-responsive mx-auto mb-5">Pour tout renseignement, merci de me contacter via ce formulaire ou par mail.</p>

    <div class="row">

        <div class="col-md-9 mb-md-0 mb-5">
          <form action="{{ route('contact.store') }}" method="POST">
                  {{ csrf_field() }}

                <div class="row">

                    <div class="col-md-6">
                        <div class="md-form mb-0">
                            <input type="text" name="nom" placeholder="Votre nom" class="form-control @error('nom') is-invalid @enderror">
                            @error('nom')
                            <div class="invalid-feedback">
                            {{ $errors->first('nom') }}
                          </div>
                          @enderror
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="md-form mb-0">
                            <input type="text" name="email" placeholder="Votre email" class="form-control @error('email') is-invalid @enderror">
                            @error('email')
                            <div class="invalid-feedback">
                            {{ $errors->first('email') }}
                          </div>
                          @enderror
                        </div>
                    </div>

                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="md-form mb-0">
                          <br><input type="text" name="sujet" placeholder="Votre sujet" class="form-control @error('sujet') is-invalid @enderror">
                          @error('sujet')
                          <div class="invalid-feedback">
                          {{ $errors->first('sujet') }}
                        </div>
                        @enderror
                      </div>
                    </div>
                </div>

                <div class="row">

                    <div class="col-md-12">

                        <div class="md-form">
                          <br><input type="text" name="message" placeholder="Votre message" class="form-control @error('message') is-invalid @enderror"></textarea>
                          @error('message')
                          <div class="invalid-feedback">
                          {{ $errors->first('message') }}
                        </div>
                        @enderror
                        </div>
                    </div>
                </div>



            <div class="text-center text-md-left">
              <br><button type="submit" class="btn btn-secondary">Envoyer</button>
            </div>
            <div class="status"></div>
            </form>
        </div>

        <div class="col-md-3 text-center">
            <ul class="list-unstyled mb-0">
                <li><i class="fas fa-map-marker-alt fa-2x"></i>
                    <p>Adresse de la boite</p>
                </li>

                <li><i class="fas fa-phone mt-4 fa-2x"></i>
                    <p>+33 6 45 87 56 32</p>
                </li>

                <li><i class="fas fa-envelope mt-4 fa-2x"></i>
                    <p>didi.maré@gmail.com</p>
                </li>
            </ul>
        </div>

    </div>

</section>
<!--Section: Contact v.2-->
@stop

resources/views/domaine/show.blade.php
@extends('template')
@section('title')
{{$domaine->libelle}}
@endsection
@section('content')

<div class="container">
    <div class="row" "zoom">
  @foreach($domaine->images as $i) <!-- ICI ;) -->
        <div class="col-4">
          <div class="image">
            <img src="{{$i->url}}" class="rounded" width=350px height=200px></img>
          </div>
        </div>
  @endforeach
    </div>
</div>
@stop

resources/views/template.blade.php
<!DOCTYPE html>
<html lang="en">

<head> <!-- site didier-->

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">


  <title>@yield('title')</title>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{{route('accueil')}}">Accueil<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{route('voir')}}">Contact</a>
        </li>
      </ul>
    </div>
  </nav>
  <!-- Navigation -->


  <!-- Page Content -->
  <div class="marge">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
        @yield('content')
        </div>
      </div>
    </div>
</div>
  <!-- Bootstrap core JavaScript -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>  <link rel="stylesheet" href="{{asset('css/style.css')}}">
</body>

</html>